### ISSUE TITLE
Character inventory bug

### ISSUE THREAD

**Issue by nqrcqn** [Stickymaddness/Procurement#1030]
I think this problem started happening after the new league, happens on both 1.27.1 and 1.26.1 whereas it didn't happen on 1.26.1 before Legion.

![image](https://user-images.githubusercontent.com/47343000/59370721-d1986580-8d4b-11e9-9ad6-c9d5449cffd2.png)

Each character inventory looks like this now and clicking on it crashes Procurement

[debug.txt](https://github.com/Stickymaddness/Procurement/files/3282431/debug.txt)

**Comment by thailyn** [comment]
Are your Standard / HC Standard stashes working properly?  Did you delete any characters?  I'm not able to recreate this with my own data.  Would you be able to zip and upload your `.bin` files, so I can examine it with your data?  They're located in the directory named after your account named used when logging in.

You can also try enabling the "Refresh on Login" button on the Procurement login screen.  That should get a fresh copy of all of your data from GGG.  My guess is there could be some data corruption or missing data that Procurement is looking for.

**Comment by nqrcqn** [comment]
All regular stashes work properly, but all of my characters on standard etc. have the same issue now for some time. I delete characters sometimes. And "Refresh on Login" is always on.


[files.zip](https://github.com/Stickymaddness/Procurement/files/3283923/files.zip)

pass: Procurement

**Comment by thailyn** [comment]
I'm able to load your bin files in offline mode without an issue, though -- and of course I forgot this nuance earlier -- I can't test refreshing.  The logging information in the debug file is also unfortunately pretty poor.  There's definitely an issue going on somewhere, as you're at least failing to download the images for the tab selector (since they show up as X's).

I added some additional logging in the draft PR #1033 that will hopefully point us in the right direction.  Could you try out that version and provide the `DebugInfo.log` file after you get errors/crashes?  Thanks!

**Comment by nqrcqn** [comment]
I replaced my char name in log with *charname*

[debug.txt](https://github.com/Stickymaddness/Procurement/files/3284356/debug.txt)

Both of the crashes seem to be caused by that 404 error.

**Comment by thailyn** [comment]
Thanks for your patience and for the additional debugging log.  I believe I've figured out the cause of the crash.  I've updated PR #1033 with additional logic to handle this case.  I haven't figured out yet why the tab image URLs are wrong and thus show up as X's, but this fix should prevent Procurement from crashing.

**Comment by nqrcqn** [comment]
crashes from clicking on inventory, after refreshing, or after excluding a tab from recipe results are all fixed now

**Comment by thailyn** [comment]
Thanks for the confirmation!  I'll clean up the PR and request for it to be merged soon.

**Comment by nqrcqn** [comment]
Off topic, Procurement seems to be using http instead of https for `webcdn.pathofexile.com` and `www.pathofexile.com` in some cases. Can we replace those just in case, though it likely doesn't fix my issue, it can be a problem regardless.

**Comment by nqrcqn** [comment]
And apparently those image links are hardcoded inside CharacterTabInjector.cs and they no longer exist there. Why not use an offline copy of those (if someone still has them) instead of downloading them?

**Comment by nqrcqn** [comment]
Indeed simplest fix for now is just copying them inside the Common folder with their original names as I found them:

[stashtab.zip](https://github.com/Stickymaddness/Procurement/files/3287110/stashtab.zip)
